language: scala

scala:
  - 2.10.7
  - 2.11.12

matrix:
  include:
  - scala: 2.12.6
    jdk: oraclejdk8

sudo: false

jdk:
  - openjdk7
  - oraclejdk8

script:
  - git config core.whitespace tab-in-indent,trailing-space,space-before-tab,cr-at-eol
  - git show --oneline --check
  - sbt ++${TRAVIS_SCALA_VERSION} test $(if [[ "${TRAVIS_PULL_REQUEST}" == "false" && ${JAVA_HOME} == $(jdk_switcher home openjdk7) && "${TRAVIS_BRANCH}" == "master" ]]; then echo "publish"; fi)

env:
  global:
  - secure: "WGM67WGPkhAXrWXZ29MT2bcq/9QB1/dMqZODQXHVVoC3k9grYJdAD9q2Q498xaJKgEDKZkX0kT0MKJ5M9e/MAkvUP+8H9uC/WDxd49CQnpEhYU0YJBj4NY81Z5VNTE80kKaF1LQXoZfha61GxUWLCKlfxVte1Avv5T56rXkE3z6XBba+cvfgBhHjJQQQasdfQ0xa1N1byTiq/40+5pyYRh0ZH71kGAIOyVIoSur77fFbjLHb7jnQeqHfO8vPiWdXPHBKTVcw02rERmehUmaUDWgJD1q4/UJ7m2WY6rvSFAXxo1aiB8K9cXxfOBRGC4lP+o8IguXl/Y/+mQngEhAnxp6pSvXCJjtOSBOpMmSahSi8N3NgcVr7I5fPqjYUWsfE0hYlxIv4vVhsEMU+JYlJLATTP/PU+ny4Vkyk5ahcPdcBF91ZQJ4JamG2Ah/mBq1m+xBQxn9AuOkD2wstTKWfdCQ4LX6u/CxaiDpHmdSglK66jaaFlf1etYjHiNrKKnTOVxbzdE/ehBuB3ZSWJykMpoQP7+kRZjdO1p0ClSPPKXUwExdyxWh5ucIeTan6mquEOmKojZGW/uOz30GxEdUL+nvyKc3c+Eqxaw5hjYFC/xfgpFSKyNmjXOUayweMynwyHcd3gVcfxkuFu3yc6tiK3c5nj5LIqNy7UG08jXawwQ0="
  - secure: "HRnF2qF94WFv2p3ziB7y6YJs05QizOm8NPb+Thf9D1E6r+84FvTufXywU1rLSHCoC6fFCoGn5nA0CwHkwYKMUu2SVUk4a6u3qSmQUQBrBTviwNWIy0b7mWt/F4bJOhmeITffzcLHZP/2g3/PwcYnYlUT6mdqti1vebq4wsNwwy3Ak6UxzfIDBHt96hxR2Dpwv1c4b3VNNZlBargVh6a/5uR3KfSALIb3pNNSbU5F2sFXjPV/lB4TvoQhog3OcDoT7FX+01Xuc+5JPUYi71QLfVnB2IDmuVVgwBgmfq1W6OPT9uyFotPWoJl8BwmAvDh8qrD3EvRYLHhEGD8+QV6F9jLXLEFkrdyYn7iLj/llDzA28ZXs6kdp4RbkO/DGAGhxz+k2WmRpXHhg3a4jq9BiU8H5CBmZ4jxsg8TmuyEuODF53zc68TnXw72kpc510udVcNFEt9+GQ3fDXfUnS+vlOnrSXLNlmmNg2nNqewLRK1y4heerMj0ixIBaCX5Cv0PV0IFIs+O9WDymGqfQq0hO8PCtqgjwqOQ/BsMUj9ClQHHuUyhxgqcqiWiKvt+rgGiWnG9QPitTL45AUraWTgXcD1h2LoX0HZ4s7kjU8Qnm6K2igr2dpgNBJQANS8bFy8M2ODmNNwbM+5/zNWp2jE9a7FDu1ATrsG+/DQipOVmM5p4="
  - secure: "MyL5vh5fZVpge4+AQ65MHEYKewFQG8+u/oDIK/QleQFuo4xkMpSYt20FMp+U5AzvOtvSfHHNvqTceR7QsRzOcuxl1iT2DcA59fQ0DcIyJaNrcYOwZsYIaEqlF8RH/xvQLG15Vs+a7FOlnSqqSFlXzt4jD4ethRGMCxpDr2WD2cmzZIm3p1AUkz4NIK4y6M/bPSXb2XuWcxDF2abTh69lSgpg9QhV/63CF80jqbQ5cptdqCqnmn5nDpSqqlM1O6eL/qdA5MiWoYEMSYaUdq1/Nlyseyo7SWL+ej7Rp/YNZvl9I5uCwzX82bp4Wq6ekfjPjqTm6K9Tc+QzbRsnm+hXc5kFOM48GzrMpa9/ixb+jH5Q2mVet3JHT/ulpqUN7RBC16blWAy8Qjg3EdLE0zmt2FyW2XJRpzL5Q2h7MpkvXLynBEJsUGOlNPTKbz1s6EACUqhSzEtMud5XQgC0U2lxWy2OS/LBabHYY1J2Lez64ScJGXcjLEUE8aEGEtOVEkXC+jHnrfvmQ4Va3ZFg5Q8d+hLJ7TAPSNaAYAWj6u5Eg2jtP0uy3qxIhgqWDvVBwB2MonYIqbNtiCOcxLgy7FP6tzRKaPIFL82LVYTevw54jWkh36c8jCXm9A1AsIuuspyE6wheEf9XxQ+aLihE+YJl5vNFrL0H/QVebw+J9L0E6+M="
